name: Build and Push Docker Images

on:
  push: 

jobs:
  push-github:
    name: Push to GHCR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Push flyte-app Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          # https://docs.github.com/en/packages/learn-github-packages/publishing-a-package
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: ${{ github.repository_owner }}/flyte-app
          image_tag: latest
          push_git_tag: true
          registry: docker.io
          build_extra_args: "--compress=true"
          context: ./
          dockerfile: Dockerfile
      - name: Push base-flyte-app Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          # https://docs.github.com/en/packages/learn-github-packages/publishing-a-package
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: ${{ github.repository_owner }}/base-flyte-app
          image_tag: latest
          push_git_tag: true
          registry: docker.io
          build_extra_args: "--compress=true"
          context: ./
          dockerfile: base.Dockerfile
